### ISSUE TITLE
unexpected response on authorization

### ISSUE THREAD

**Issue by armanobosyan** [asiunov/boomstream-downloader#1]
https://github.com/cleeque/boomstream-downloader/issues/5
Moving issue to forked boomstream-downloader

Current content does not require PIN. For example and test please use: el4Eh2sj
Error message: 

Traceback (most recent call last):
File "./boomstream.py", line 312, in
sys.exit(app.run())
File "./boomstream.py", line 278, in run
cookies = self.get_access_cookies()
File "./boomstream.py", line 269, in get_access_cookies
raise ValueError(f"unexpected response on authorization: {r.text}")
ValueError: unexpected response on authorization: {"code":500,"message":"Internal Server Error"}

**Comment by armanobosyan** [comment]
Fixed in Latest commit c6b9b02

THANK YOU!
